# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/templates/mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1645, 660)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.roiXInput = QtGui.QDoubleSpinBox(self.groupBox)
        self.roiXInput.setDecimals(0)
        self.roiXInput.setMaximum(999999999.0)
        self.roiXInput.setObjectName(_fromUtf8("roiXInput"))
        self.horizontalLayout_2.addWidget(self.roiXInput)
        self.roiYInput = QtGui.QDoubleSpinBox(self.groupBox)
        self.roiYInput.setDecimals(0)
        self.roiYInput.setMaximum(999999999.0)
        self.roiYInput.setObjectName(_fromUtf8("roiYInput"))
        self.horizontalLayout_2.addWidget(self.roiYInput)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        self.clearModeSelect = QtGui.QComboBox(self.groupBox)
        self.clearModeSelect.setObjectName(_fromUtf8("clearModeSelect"))
        self.gridLayout_3.addWidget(self.clearModeSelect, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.roiXOffsetInput = QtGui.QDoubleSpinBox(self.groupBox)
        self.roiXOffsetInput.setDecimals(0)
        self.roiXOffsetInput.setMaximum(999999999.0)
        self.roiXOffsetInput.setObjectName(_fromUtf8("roiXOffsetInput"))
        self.horizontalLayout_3.addWidget(self.roiXOffsetInput)
        self.roiYOffsetInput = QtGui.QDoubleSpinBox(self.groupBox)
        self.roiYOffsetInput.setDecimals(0)
        self.roiYOffsetInput.setMaximum(999999999.0)
        self.roiYOffsetInput.setObjectName(_fromUtf8("roiYOffsetInput"))
        self.horizontalLayout_3.addWidget(self.roiYOffsetInput)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 6, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 6, 0, 1, 1)
        self.readoutRateSelect = QtGui.QComboBox(self.groupBox)
        self.readoutRateSelect.setObjectName(_fromUtf8("readoutRateSelect"))
        self.gridLayout_3.addWidget(self.readoutRateSelect, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.resetRoiButton = QtGui.QPushButton(self.groupBox)
        self.resetRoiButton.setObjectName(_fromUtf8("resetRoiButton"))
        self.horizontalLayout_4.addWidget(self.resetRoiButton)
        self.setRoiButton = QtGui.QPushButton(self.groupBox)
        self.setRoiButton.setObjectName(_fromUtf8("setRoiButton"))
        self.horizontalLayout_4.addWidget(self.setRoiButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 7, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.exposureInput = QtGui.QDoubleSpinBox(self.groupBox)
        self.exposureInput.setMaximum(999999999.0)
        self.exposureInput.setObjectName(_fromUtf8("exposureInput"))
        self.gridLayout_3.addWidget(self.exposureInput, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.triggerModeSelect = QtGui.QComboBox(self.groupBox)
        self.triggerModeSelect.setObjectName(_fromUtf8("triggerModeSelect"))
        self.gridLayout_3.addWidget(self.triggerModeSelect, 2, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 4, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cameraViewFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cameraViewFrame.sizePolicy().hasHeightForWidth())
        self.cameraViewFrame.setSizePolicy(sizePolicy)
        self.cameraViewFrame.setFrameShape(QtGui.QFrame.Box)
        self.cameraViewFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.cameraViewFrame.setObjectName(_fromUtf8("cameraViewFrame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.cameraViewFrame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout.addWidget(self.cameraViewFrame, 1, 0, 1, 3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.liveCameraButton = QtGui.QPushButton(self.centralwidget)
        self.liveCameraButton.setObjectName(_fromUtf8("liveCameraButton"))
        self.horizontalLayout_5.addWidget(self.liveCameraButton)
        self.snapFrameButton = QtGui.QPushButton(self.centralwidget)
        self.snapFrameButton.setObjectName(_fromUtf8("snapFrameButton"))
        self.horizontalLayout_5.addWidget(self.snapFrameButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cameraFramesInput = QtGui.QSpinBox(self.centralwidget)
        self.cameraFramesInput.setMaximum(999999999)
        self.cameraFramesInput.setObjectName(_fromUtf8("cameraFramesInput"))
        self.horizontalLayout_7.addWidget(self.cameraFramesInput)
        self.cameraFramesRecordButton = QtGui.QPushButton(self.centralwidget)
        self.cameraFramesRecordButton.setObjectName(_fromUtf8("cameraFramesRecordButton"))
        self.horizontalLayout_7.addWidget(self.cameraFramesRecordButton)
        self.bgSubstracionFramesInput = QtGui.QSpinBox(self.centralwidget)
        self.bgSubstracionFramesInput.setMaximum(999999999)
        self.bgSubstracionFramesInput.setObjectName(_fromUtf8("bgSubstracionFramesInput"))
        self.horizontalLayout_7.addWidget(self.bgSubstracionFramesInput)
        self.cameraBgSubstractionButton = QtGui.QPushButton(self.centralwidget)
        self.cameraBgSubstractionButton.setObjectName(_fromUtf8("cameraBgSubstractionButton"))
        self.horizontalLayout_7.addWidget(self.cameraBgSubstractionButton)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.graphViewFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphViewFrame.sizePolicy().hasHeightForWidth())
        self.graphViewFrame.setSizePolicy(sizePolicy)
        self.graphViewFrame.setFrameShape(QtGui.QFrame.Box)
        self.graphViewFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.graphViewFrame.setObjectName(_fromUtf8("graphViewFrame"))
        self.gridLayout_5 = QtGui.QGridLayout(self.graphViewFrame)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2.addWidget(self.graphViewFrame, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.horizontalLayout_9.addWidget(self.startButton)
        self.refreshButton = QtGui.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.horizontalLayout_9.addWidget(self.refreshButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.saveGraphButton = QtGui.QPushButton(self.centralwidget)
        self.saveGraphButton.setObjectName(_fromUtf8("saveGraphButton"))
        self.horizontalLayout_11.addWidget(self.saveGraphButton)
        self.graphFramesRecordInput = QtGui.QSpinBox(self.centralwidget)
        self.graphFramesRecordInput.setMaximum(999999999)
        self.graphFramesRecordInput.setObjectName(_fromUtf8("graphFramesRecordInput"))
        self.horizontalLayout_11.addWidget(self.graphFramesRecordInput)
        self.recordGraphButton = QtGui.QPushButton(self.centralwidget)
        self.recordGraphButton.setObjectName(_fromUtf8("recordGraphButton"))
        self.horizontalLayout_11.addWidget(self.recordGraphButton)
        self.saveImagesCheckbox = QtGui.QCheckBox(self.centralwidget)
        self.saveImagesCheckbox.setObjectName(_fromUtf8("saveImagesCheckbox"))
        self.horizontalLayout_11.addWidget(self.saveImagesCheckbox)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1645, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuApplication = QtGui.QMenu(self.menubar)
        self.menuApplication.setObjectName(_fromUtf8("menuApplication"))
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuApplication.addAction(self.actionExit)
        self.menubar.addAction(self.menuApplication.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.resetRoiButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.resetRoi)
        QtCore.QObject.connect(self.setRoiButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.setRoi)
        QtCore.QObject.connect(self.clearModeSelect, QtCore.SIGNAL(_fromUtf8("editTextChanged(QString)")), MainWindow.clearModeChanged)
        QtCore.QObject.connect(self.triggerModeSelect, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.triggerModeChanged)
        QtCore.QObject.connect(self.readoutRateSelect, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), MainWindow.readoutRateChanged)
        QtCore.QObject.connect(self.exposureInput, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), MainWindow.exposureTimeChanged)
        QtCore.QObject.connect(self.liveCameraButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.liveModeClicked)
        QtCore.QObject.connect(self.snapFrameButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.snapClicked)
        QtCore.QObject.connect(self.cameraFramesRecordButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cameraRecordClicked)
        QtCore.QObject.connect(self.cameraBgSubstractionButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.bgSubstracionClicked)
        QtCore.QObject.connect(self.refreshButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.refreshClicked)
        QtCore.QObject.connect(self.saveGraphButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.graphSaveClicked)
        QtCore.QObject.connect(self.recordGraphButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.recordGraphClicked)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.startButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.start)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Camera settings", None))
        self.roiXInput.setSuffix(_translate("MainWindow", " px", None))
        self.roiYInput.setSuffix(_translate("MainWindow", " px", None))
        self.label_4.setText(_translate("MainWindow", "Clear Mode:", None))
        self.label.setText(_translate("MainWindow", "Exposure Time:", None))
        self.roiXOffsetInput.setSuffix(_translate("MainWindow", " px", None))
        self.roiYOffsetInput.setSuffix(_translate("MainWindow", " px", None))
        self.label_6.setText(_translate("MainWindow", "Roi offset:", None))
        self.label_2.setText(_translate("MainWindow", "Readout Rate", None))
        self.resetRoiButton.setText(_translate("MainWindow", "Reset ROI", None))
        self.setRoiButton.setText(_translate("MainWindow", "Set ROI", None))
        self.label_5.setText(_translate("MainWindow", "Roi size:", None))
        self.exposureInput.setSuffix(_translate("MainWindow", " ms", None))
        self.label_3.setText(_translate("MainWindow", "Trigger Mode:", None))
        self.liveCameraButton.setText(_translate("MainWindow", "Live", None))
        self.snapFrameButton.setText(_translate("MainWindow", "Snap", None))
        self.cameraFramesRecordButton.setText(_translate("MainWindow", "Record", None))
        self.cameraBgSubstractionButton.setText(_translate("MainWindow", "Bg. Substraction", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.refreshButton.setText(_translate("MainWindow", "Refresh", None))
        self.saveGraphButton.setText(_translate("MainWindow", "Save", None))
        self.recordGraphButton.setText(_translate("MainWindow", "Record", None))
        self.saveImagesCheckbox.setText(_translate("MainWindow", "Save images", None))
        self.menuApplication.setTitle(_translate("MainWindow", "Application", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

